### post products
POST http://localhost:4000/product-api/product
Content-Type: application/json

{
     "productName":"Mobile Phone",
     "price":100000,
     "brand":"Apple"
}

### get products
GET http://localhost:4000/product-api/product


###Create req user
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
     "name":"vardhan",
     "email":"bollavardhanreddy26@gmail.com",
     "password":"vardhan@123",
     "cart":[]
}

### get users
GET http://localhost:4000/user-api/user

### add product to cart
PUT http://localhost:4000/user-api/user-cart/user-id/69834fd612ad2e3c7cddc5b4/product-id/69834fbc12ad2e3c7cddc5b0


###read user id
GET http://localhost:4000/user-api/user/69834fd612ad2e3c7cddc5b4