###User:
POST http://localhost:4000/author-api/users
Content-Type: application/application/json

{
    'firstName':"Vardhan",
    'lastName':"Author",
    'email':"vardhan@gmail.com",
    'password':"vardhan@123#",
    'role':"USER",
    'isactive':true,
}