GET http://localhost:3000/user-api/users
###

POST http://localhost:3000/user-api/user/id
Content-Type: application/json

{
    "id":100,
    "name":"VardhanReddy",
    "age":21
}

###
PUT http://localhost:3000/user-api/user/id
Content-Type: application/json

{
    "id":101,
    "name":"vardhanReddy",
    "age":22
}

###
//Read a user by id
GET http://localhost:3000/user-api/users/100



###
DELETE http://localhost:3000/user-api/user/100

###
GET  http://localhost:3000/product-api/products

###
GET  http://localhost:3000/product-api/product/id

###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "id":"102",
    "name":" Mackbook Pro",
    "price":100000,
    "brand":"Apple"
}

###
PUT http://localhost:3000/product-api/products/id
Content-Type: application/json

{
    "id":"101",
    "name":"Mackbook Pro-updated",
    "price":90000,
    "brand":"Apple"
}

###
DELETE http://localhost:3000/product-api/products/101